### ISSUE TITLE
Deep link support when coordinators share the same root viewcontroller

### ISSUE THREAD

**Issue by andschdk** [quickbirdstudios/XCoordinator#149] opened 2019-12-05 08:46 UTC
Sharing the same root view controller (e.g. `UINavigationController`) is easy and documented in this section: https://github.com/quickbirdstudios/XCoordinator#using-multiple-coordinators-with-the-same-rootviewcontroller

I was wondering how deep linking works in this case, as the `.none()` transition will "break the chain" from what I experienced, because the transition does not deliver anything for the "context completion callback".

As an example say we have this deeplink (based on Example app):
__AppRoute.home -> HomeRoute.userList -> UserListRoute.about -> AboutRoute.website__

This is how the stack looks like
__AppCoordinator -> HomeViewController -> AboutCoordinator -> AboutViewController -> ⚠️ Crash__

When the router for `.website` is being resolved no router is found in the stack because the `AboutCoordinator` was added using the `.none()` transition.

How to solve this case? Let me know what you think. Thanks.

**Comment by pauljohanneskraft** [comment] 2019-12-05 09:00
Possible duplicate of https://github.com/quickbirdstudios/XCoordinator/issues/145.

**Comment by andschdk** [comment] 2019-12-05 09:15
Thanks @pauljohanneskraft 👍 
I solved it by modifying the `.none()` transition like so:
```swift
    public static func none(presentables: [Presentable] = []) -> Transition {
        return Transition(presentables: presentables) { _, _, completion in
            completion?()
        }
    }
```

I guess you should still `addChild(coordinator)` when preparing the transition, in #145 you left it out?
Do you have plans for supporting this case in a future release?

**Comment by pauljohanneskraft** [comment] 2019-12-05 09:20
You do not need it, since `addChild` is called for all `presentables` of a Transition already.
We are currently thinking about adding such a functionality - we will however need to investigate how to solve this properly (i.e. without relying on BaseCoordinator-specific properties). We will let you know once this feature has been added.

**Closed by pauljohanneskraft** 2019-12-05 09:20 UTC
Labels: question

**Comment by ashikase** [comment] 2020-02-19 08:29
There appears to be an issue with this solution, in that the child coordinator is not removed from the parent's `children` array after the child is no longer in use (e.g. popped).

This seems to be due to the fact that the parent and child share the same `viewController` (e.g. the `UINavigationController` instance), and so the function `canBeRemovedAsChild()` will return false for the child because `viewController.isInViewHierarchy` will return true.

**Comment by andschdk** [comment] 2020-12-17 08:46
I think @ashikase is right. 
@pauljohanneskraft should this or #145 be reopened?
