### ISSUE TITLE
Can not build with Carthage

### ISSUE THREAD

**Issue by lexrus** [quickbirdstudios/XCoordinator#49] opened 2019-01-04 06:02 UTC
<img width="643" alt="screen shot 2019-01-04 at 2 01 38 pm" src="https://user-images.githubusercontent.com/219689/50675478-5e1a5b80-1029-11e9-9650-7e5adbc82172.png">

**Comment by pauljohanneskraft** [comment] 2019-01-04 15:41
Duplicate of #47 - will be fixed in the next release.

**Closed by pauljohanneskraft** 2019-01-04 15:41 UTC
