### ISSUE TITLE
File 'Router+Rx.swift' is part of module 'XCoordinator'; ignoring import

### ISSUE THREAD

**Issue by Daewooox** [quickbirdstudios/XCoordinator#202] opened 2021-02-09 08:39 UTC
Hey!
Just get warning File 'Router+Rx.swift' is part of module 'XCoordinator'; ignoring import
<img width="1224" alt="Screen Shot 2021-02-09 at 11 37 12 AM" src="https://user-images.githubusercontent.com/25296264/107337358-498fd380-6acb-11eb-9ff7-f85727a2c593.png">

**Comment by pauljohanneskraft** [comment] 2021-04-21 09:24
Hey - I just tried it again and I don't seem to get the same warning... can you send me your Podfile (or at least the relevant parts), so that I can further investigate here?

**Comment by pauljohanneskraft** [comment] 2021-05-27 23:51
I have tried this again and could reproduce the warnings. However, you can safely ignore the warning and it will go away when building again. I will close this issue, since we will not easily be able to fix this (with Swift Package Manager and Cocoapods both working as expected).

**Closed by pauljohanneskraft** 2021-05-27 23:51 UTC
